services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sveltekit
  sveltekit:
    build:
      context: .
      dockerfile: docker/sveltekit/Dockerfile
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - .:/app
